version: "3"
services:
  application:
    image: student
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/student

  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=Emami@4321
      - MYSQL_DATABASE=test
    volumes:
      - /data/mysql
networks:
  springboot-db-net: